name: Production Subgraph (Sepolia)

on:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/template-deploy.yaml
    with:
      ENVIRONMENT: production-sepolia
      CONFIG: sepoliaAddressScript.ts
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.graphprotocol_npm_token }}
      ACCESS_TOKEN: ${{ secrets.access_token }}
