name: Production Subgraph (Rinkeby)

on:
  push:
    branches:
      - mainnet-staging

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    uses: graphprotocol/graph-network-subgraph/.github/workflows/template-deploy.yaml@master
    with:
      ENVIRONMENT: testnet
      CONFIG: rinkebyAddressScript.ts
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.graphprotocol_npm_token }}
      ACCESS_TOKEN: ${{ secrets.access_token }}
