name: Production Subgraph Non-IPFS (Mainnet)

on:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/template-deploy.yaml
    with:
      ENVIRONMENT: production-no-ipfs
      CONFIG: mainnetAddressScript.ts
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.graphprotocol_npm_token }}
      ACCESS_TOKEN: ${{ secrets.access_token }}
