name: Staging Subgraph (Mainnet)

on:
  push:
    branches:
      - mainnet-staging

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/template-deploy.yaml
    with:
      ENVIRONMENT: staging-mainnet
      CONFIG: mainnetAddressScript.ts
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.graphprotocol_npm_token }}
      ACCESS_TOKEN: ${{ secrets.access_token }}
