name: Tests (L1)

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install commands
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          registry-url: https://registry.npmjs.org
      - name: yarn add ts-node
        run: yarn add ts-node
      - name: yarn install
        run: yarn install

      # Run scripts
      - name: Prep NO IPFS
        run: ./node_modules/.bin/mustache ./config/no-ipfs.json ./src/mappings/helpers/metadata.template.ts > ./src/mappings/helpers/metadata.ts
      - name: Prep addressess
        run: ./node_modules/.bin/ts-node config/testAddressesL1.ts && ./node_modules/.bin/mustache ./config/generatedAddresses.json ./config/addresses.template.ts > ./config/addresses.ts
      - name: Prep test L1
        run: ./node_modules/.bin/mustache ./config/generatedAddresses.json subgraph.template.yaml > subgraph.yaml && ./node_modules/@graphprotocol/graph-cli/bin/run codegen --output-dir src/types/
      - name: Test
        run: ./node_modules/@graphprotocol/graph-cli/bin/run test -v 0.6.0-rc.2
